# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(max_length=50)),
                ('visitor_number', models.CharField(max_length=12)),
                ('visitor_email', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('host_number', models.CharField(max_length=12)),
                ('host_email', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(default=None)),
            ],
        ),
    ]
